### ISSUE TITLE
Action adopt name change

### ISSUE THREAD

**Issue by BenPapple** [agentcontest/massim_2022#4]
In the GOAL agent programmig language "adopt" is already a GOAL specific keyword and so can't be used as an action.

I suggest a name change or a different shadow action doing the same as "adopt" under a different name while keeping adopt for other programming languages.

**Comment by t-ah** [comment]
Good to know.
7c7ff3fe749c82eb0c8dea2a901fcdb845ee767f should introduce an alias (adapt) for the adopt action.
